var options = [
				[
					[ //SINGLE PROTAGONIST
						"A man",
						"A woman",
						"A family",
						"An unnamed protagonist",
						"A prairie nun",
						"A schoolteacher",
						"An orphan",
						"Drake",
						"A teenager",
						"A dog",
						"A person with an antiquated profession",
						"A 21 year-old dissatisfied with their life of privilege",
						"A husband",
						"A survivor of the Halifax Explosion",
						"A statue of Louis Riel",
						"A small town preacher",
						"Rick the Temp",
						"A Port Dover fish farmer",
						"A fur trapper",
						"A time traveler",
						"A wife",
						"The daughter of an MP",
						"One of the Eatons",
						"A Bell employee",
						"A sea captain",
						"A new immigrant",
						"A recently-retired RCMP officer",
						"A lifelong city dweller",
						"The owner of a struggling small business",
						"A lonely widower",
						"A writer"
					], [//SINGLE ACTION
						" drives across the country",
						" crosses the Rockies",
						" explores the Maritimes",
						" journeys to the center of Algonquin Park",
						" goes to Frobisher Bay",
						" has to leave Frobisher Bay",
						" goes to an abandoned Yukon Gold Rush town",
						" visits a dilapidated farmhouse on the Prairies",
						" tries to live",
						" makes peace with their past",
						" gets lost in the northern Quebec wilderness",
						" falls through the ice",
						" learns to run a farm",
						" goes hunting",
						" breaks into a cottage in the Muskokas",
						// " solves crimes",
						" dries a tea cup",
						" gets government funding",
						" smuggles rum",
						" contemplates their provincial identity",
						" survives a historical tragedy",
						" tries acid at a concert",
						" builds a small-town church",
						" learns to salt and cure cod",
						" contemplates the meaning of Tim Horton's coffee",
						" ages gracelessly",
						" falls in love with a wild animal",
						" lives a metaphor",
						" builds the 2nd tallest lighthouse in Atlantic Canada",
						" writes Laura Secord erotic fan-fiction",
						" is haunted by memories and maybe a real ghost",
						" visits rich New York relations ",
						" becomes involved in the fur trade",
						" eats poutine at a fictionalized version of a diner in your town you totally recognize and for some reason feel that you knowing that place is somehow a flaw of the story,",
						" raises a sheep that may or may not talk",
						" abandons an unfinished novel",
						" drives drunk",
						" learns music to express themselves",
						" abandons their life in the Oil Patch",
						// " transforms into a moose",
						" solves a mystery",
						" disappears mysteriously",
						" buys a notebook at a thrift store",
						" travels to Yellowknife",
						" attempts to make it to a Drake concert",
						// " marries a sea captain",
						" spends 455 pages wandering through that desert in Quebec, you know the one,",
						" meets a BC woman who never takes off her hiking gear",
						// " silently struggles with identity",
						" buries a memento in the dirt outside their childhood home",
						" plans a white-collar crime",
						" battles with a Wendigo",
						// " struggles with what it means to be Canadian"
					], [ //SINGLE REASON
						", but only after multiple scenes of ice skating.",
						" to learn the darkest secrets of their family.",
						", disillusioned with the pace and emptiness of urban living.",
						", after spending the first scene staring moodily out the kitchen window.",
						" and falls in love with a neighbor.",
						" to better know their withdrawn, uncommunicative father.",
						" to make peace with the parents they never knew.",
						" to bring medicine to their snowed-in family.",
						" while working for the Hudson's Bay Company.",
						" to rediscover themselves at the family cabin.",
						" to survive the harsh winter and their failing marriage.",
						", haunted by the spectre of their grandfather's mistakes.",
						" only to return with a broken soul.",
						", barely escaping the weather.",
						" but in a 'Little Mosque on the Prairie' kind of way.",
						" and... I don't know, something about the sins of the father.",
						" only to be beset by the spirits of their ancestors.",
						" to try to find the way home.",
						" and plans a divorce.",
						" under a pall of heavily-implied incest",
						" to find themselves.",
						" after the fishery collapses.",
						" to fund a sod house.",
						" but is also a robot.",
						" to recover the letters of their lost love.",
						" despite the wishes of a wealthy father.",
						" despite the wishes of a poor father.",
						" despite the wishes of a loving father.",
						" despite an absent father.",
						//" with Mennonites.",
						//" with surprisingly few negative results.",
						" to make it to a funeral for someone they lost touch with years before.",
						" without realizing that Drake references aren't inherently hip or funny.",
						" with sexy results.",
						" which results in the death of half of The Tragically Hip.",
						" which they then adopt as their own.",
						" only to lose it all at sea.",
						" only to have to kill a whale.",
						" only to be killed by Vikings.",
						", discovering that wilderness can never be really tamed.",
						" to reconnect with the false, nostalgic simplicity of their youth.",
						", learning that surviving is a victory all its own.",
						", losing an arm for their troubles.",
						", finding community where one would least expect.",
						" to provide care for their ailing mother.",
						" and maybe has sex with a bear&mdash; unless that was a dream, I never can tell."
					], [ //SINGLE MODE
						"",
						" on a motorcycle",
						" in an RV",
						" on a stolen houseboat",
						" in 1897",
						" during the War",
						" in a Bennett buggy",
						" in a one room cabin",
						" in a tallship",
						" on a shitty Greyhound bus",
						", appearing on Breakfast Television",
						" on a skidoo",
						" on a dog sled",
						" on a plane to Vancouver",
						" in a pickup truck",
						" in excruciatingly-detailed Toronto",
						" in a squid-jiggin' boat",
						" in the Great Depression",
						" during the Great Fire of Toronto",
						" in the Day-Glo version of Newfoundland they show you in the tourism ads"
					], [ //tersely
						"",
						" tersely"
					]
				],[
					[	//PLURAL PROTAGONIST
						"A troupe of French-Canadian clowns",
						"A man and his dog",
						"Two dogs",
						"A woman and her dog",
						"A group of writers",
						"Three undergraduates from diverse backgrounds",
						"An intramural soccer team",
						"A family and their dog",
						"Three generations of an East Coast family"
					], [//PLURAL ACTION
						" drive across the country",
						" cross the Rockies",
						" explore the Maritimes",
						" journey to the center of Algonquin Park",
						" go to Frobisher Bay",
						" have to leave Frobisher Bay",
						" go to an abandoned Yukon Gold Rush town",
						" visit a dilapidated farmhouse on the Prairies",
						" try to live",
						" get lost in the wilds of northern Quebec",
						" fall through the ice",
						" go hunting",
						" break into a cottage in the Muskokas",
						// " solve crimes",
						" dry a tea cup",
						" get government funding ",
						" smuggle rum",
						" contemplate their provincial identity",
						" survive a historical tragedy",
						" try acid at a concert",
						" build a small-town church",
						" learn to salt and cure cod",
						" contemplate the meaning of Tim Horton's coffee",
						" conduct a maple syrup heist",
						" age gracelessly",
						" fall in love with a wild animal",
						" live a metaphor",
						" build the 2nd tallest lighthouse in Atlantic Canada",
						" write Laura Secord erotic fan-fiction",
						" are haunted by memories and maybe a real ghost",
						" visit rich New York relations",
						" become involved in the fur trade",
						" eat poutine at a fictionalized version of a diner in your town you totally recognize and for some reason feel that you knowing that place is somehow a flaw of the story",
						" raise a sheep that may or may not talk",
						" cannot finish their novel",
						" drive drunk",
						" lay an egg",
						" transform into a moose",
						" solve a mystery",
						" disappear mysteriously",
						" travel to Yellowknife",
						" attempt to make it to a Drake concert",
						" marry a sea captain",
						" spend 455 pages wandering that desert in Quebec",
						" meet a BC woman who never takes off her MEC hiking gear",
						" struggle with what it means to be both Canadian and Other",
						" bury a memento in the dirt outside their childhood home",
						" return to their small town home",
						" fall in love with a mermaid",
						" learn fairies are real",
						" battle with a Wendigo",
						" struggle with what it means to be Canadian"
					], [ //PLURAL RESULT
						" to learn the darkest secrets of their family.",
						", but only after multiple scenes of ice skating.",
						", disillusioned with the pace and emptiness of urban living.",
						" to better know their withdrawn, uncommunicative father.",
						" to make peace with the parents they never knew.",
						" to bring medicine to their snowed in family.",
						" while working for the Hudson's Bay Company.",
						" to survive the harsh winter and their failing marriage.",
						", haunted by the spectre of their grandfather's mistakes.",
						", barely escaping the weather.",
						" only to return with a broken soul.",
						" but in a 'Little Mosque on the Prairie' kind of way.",
						" and... I don't know, something about the sins of the father.",
						" only to be beset by the spirits of their ancestors.",
						" to try to find the way home.",
						" and plans a divorce.",
						" under the pall of heavily implied incest",
						" to find themselves.",
						" after the fishery collapsed.",
						" to fund a sod house.",
						" but also, one of them is a robot.",
						" despite a wealthy father.",
						" despite a poor father.",
						" despite a loving father.",
						" despite an absent father.",
						" with Mennonites.",
						" with surprisingly few negative results.",
						" to make it to a funeral.",
						" without realizing that Drake references aren't inherently hip or funny.",
						" with sexy results.",
						" which results in the death of half of The Tragically Hip.",
						" which they then adopt as their own.",
						" only to lose it all at sea.",
						" only to be forced into a life-and-death struggle with a whale.",
						" only to be killed by Vikings.",
						", discovering that wilderness can never be really tamed.",
						" to reconnect with the false, nostalgic simplicity of their youth.",
						", learning that surviving is a victory all its own.",
						", losing an arm for their troubles.",
						", after spending the first scene staring moodily out the kitchen window.",	
						" to rediscover themselves at the family cabin.",
						" to provide care for their mother.",
						", finding community where one would least expect.",
						" and maybe have sex with a bear&mdash; unless that was a dream? I can never tell."
					], [//PLURAL MODE
						"",
						" on a motorcycle",
						" in an RV",
						" on a stolen houseboat",
						" in 1897",
						" during the War",
						" in a Bennett buggy",
						" in a one room cabin",
						" in a tallship",
						" on a shitty Greyhound bus",
						", appearing on Breakfast Television",
						" on a skidoo",
						" on a dog sled",
						" on a plane to Vancouver",
						" in a pickup truck",
						" in excruciatingly detailed Toronto",
						" in a squid-jiggin' boat",
						" in the Great Depression",
						" during the Great Fire of Toronto",
						" in the Day-Glo version of Newfoundland they show you in the tourism ads"
					], [ // TERSELY
						"",
						" tersely"
					]				
				]
			];